// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  instagramUrl?: string
  facebookUrl?: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  logoUrl?: string
  photos: string[]
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  about: {
    heading: string
    body: string
    ownerName: string
  }
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'MG Roofing & services LTD',
  trade: 'Roofers',
  tagline: 'Expert Roofing Solutions Across Manchester',
  phone: '+44 7514 471046',
  email: 'contact@mgroofingservices.com',
  address: '',
  city: 'Manchester',
  serviceArea: 'Manchester',
  googleBusinessUrl: 'https://www.google.com/maps/search/?api=1&query=MG%20Roofing%20%26%20services%20LTD&query_place_id=ChIJa-DleXHhNGYRoWG0ldAZcLM',
  instagramUrl: 'https://www.instagram.com/aiwithdennis',
  facebookUrl: 'https://www.facebook.com/leadplug/',
  yearsExperience: 0,
  logoUrl: 'https://mgroofingservices.com/wp-content/uploads/2023/03/cropped-MG-180x180.png',
  photos: ["https://mgroofingservices.com/wp-content/uploads/2023/03/MG-ROOFING-180-\u00d7-60px-3-167x73.png", "https://mgroofingservices.com/wp-content/uploads/2023/03/MG-ROOFING-180-\u00d7-60px-4.png", "https://mgroofingservices.com/wp-content/uploads/2023/03/Untitled-design-28.png", "https://mgroofingservices.com/wp-content/uploads/2025/10/New-Roof-300x128.webp", "https://mgroofingservices.com/wp-content/uploads/2023/03/MG-ROOFING-180-\u00d7-60px-4-1.png", "https://mgroofingservices.com/wp-content/uploads/2023/03/MG-ROOFING-180-\u00d7-60px-3.png"],

  variant: 'B',

  hero: {
    heading: 'Manchester\'s Trusted Roofers for Quality Workmanship',
    subheading: 'MG Roofing & Services LTD provides professional roofing solutions throughout Manchester. We\'re fully insured, locally based, and committed to delivering outstanding results with 24/7 availability for emergencies.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix leaks, damaged tiles, and structural issues quickly and effectively. Our repair work is designed to last and protect your property from further damage.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Complete roof replacement using quality materials and proven techniques. We handle everything from planning to completion, ensuring your new roof meets the highest standards.',
    },
    {
      iconName: 'Droplets',
      name: 'Guttering Services',
      description: 'Professional gutter cleaning, repairs, and replacement to protect your property from water damage. We ensure proper drainage and maintain the integrity of your roofing system.',
    },
    {
      iconName: 'Shield',
      name: 'Emergency Repairs',
      description: '24/7 emergency response for urgent roofing problems that can\'t wait. We\'ll secure your property quickly and arrange permanent repairs at the earliest opportunity.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough assessments to identify potential problems before they become costly repairs. Our detailed reports help you maintain your roof and plan for any necessary work.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Maintenance',
      description: 'Regular maintenance services to extend your roof\'s lifespan and prevent unexpected issues. We provide scheduled check-ups and maintenance plans tailored to your property\'s needs.',
    },
  ],

  trustItems: [
    'Fully Insured',
    'Free Quotes',
    'Local to Manchester',
    'Work Guaranteed'
  ],

  whyUs: {
    heading: 'Why Choose MG Roofing & Services LTD?',
    subheading: 'We\'re Manchester\'s reliable roofing specialists, combining quality workmanship with honest, transparent service that you can trust.',
    points: [
      {
        heading: 'Local Expertise',
        body: 'Based in Manchester, we understand local weather conditions and building requirements. Our knowledge of the area means we can recommend the best solutions for your specific needs.',
      },
      {
        heading: 'Quality Materials',
        body: 'We use only high-grade materials from trusted suppliers to ensure lasting results. Every project benefits from our commitment to quality and attention to detail.',
      },
      {
        heading: 'Transparent Pricing',
        body: 'No hidden costs or surprise charges with our clear, upfront pricing. We provide detailed quotes so you know exactly what you\'re paying for.',
      },
      {
        heading: 'Reliable Service',
        body: 'We turn up when we say we will and complete work to schedule. Our 24/7 availability means we\'re here when you need us most.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a quote online to discuss your roofing needs. We\'ll arrange a convenient time to assess your property and provide expert advice.',
    },
    {
      heading: 'Free Assessment',
      body: 'Our experienced roofers will inspect your roof and identify any issues or requirements. We\'ll explain our findings in plain English and recommend the best course of action.',
    },
    {
      heading: 'Detailed Quote',
      body: 'Receive a clear, itemised quote with no hidden costs or surprises. We\'ll explain all work included and answer any questions you may have.',
    },
    {
      heading: 'Quality Work',
      body: 'Our skilled team completes your roofing project to the highest standards. We keep you informed throughout and ensure minimal disruption to your daily routine.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you respond to emergency roof repairs?',
      answer: 'We offer 24/7 emergency response for urgent roofing issues. Our team can typically attend emergency callouts within a few hours to secure your property and prevent further damage.',
    },
    {
      question: 'Do you provide free quotes for roofing work?',
      answer: 'Yes, we provide free, no-obligation quotes for all roofing services. Our assessments include a thorough inspection and detailed written estimate with transparent pricing.',
    },
    {
      question: 'What types of roofing materials do you work with?',
      answer: 'We work with all common roofing materials including tiles, slates, felt, and metal roofing systems. Our team has experience with both traditional and modern roofing solutions.',
    },
    {
      question: 'Are you fully insured for roofing work?',
      answer: 'Yes, we carry full public liability insurance and employer\'s liability cover. This protects both our customers and our team during all roofing projects.',
    },
    {
      question: 'Do you clean up after completing roofing work?',
      answer: 'Absolutely. We take pride in leaving your property clean and tidy after every job. All debris and materials are removed, and the surrounding area is thoroughly cleaned.',
    },
    {
      question: 'Can you work on commercial as well as residential properties?',
      answer: 'Yes, we handle both residential and commercial roofing projects throughout Manchester. Our team has experience with various property types and roofing systems.',
    },
  ],

  about: {
    heading: 'About MG Roofing & Services LTD',
    body: 'I established MG Roofing & Services LTD to provide Manchester homeowners and businesses with honest, reliable roofing services. Having worked in the local area, I understand how important it is to have a roof you can trust, especially with Manchester\'s changeable weather. I\'m committed to delivering quality workmanship and treating every property as if it were my own.',
    ownerName: 'The MG Roofing Team — Owner',
  },

  reviews: [
    {
      name: 'Shambel W.',
      rating: 5,
      text: 'They doing good job changing my roof.',
      date: '',
    },
    {
      name: 'shahzaib m.',
      rating: 5,
      text: 'The work is impeccable no more leak  thank you',
      date: '',
    },
    {
      name: 'Mohammed K.',
      rating: 5,
      text: 'Excellent service really quick worker unbelievable good prices highly recommended',
      date: '',
    },
    {
      name: 'Shankar B.',
      rating: 5,
      text: 'I recently had an excellent experience with MG Roofing. They arrived promptly at the scheduled time and exhibited a high level of professionalism. The team was incredibly polite and well-mannered, making the entire process smooth and enjoyable.\n\nWhat stood out the most was their competitive pricing; I found their rates to be the best in the area. I highly recommend MG Roofing for anyone in need of roofing services . Their combination of punctuality, courtesy, and affordability truly sets them apart!',
      date: '',
    },
    {
      name: 'Frad F.',
      rating: 5,
      text: 'I recently used MG Roofing Company to repair the roof on my shop. The team arrived on time and were very professional. They explained the issue clearly and fixed the roof quickly and efficiently. The quality of the work was very good and they left everything clean after finishing. I’m very happy with the service and would definitely recommend MG Roofing Company to anyone who needs roof repairs.',
      date: '',
    },
  ],

  seo: {
    title: 'MG Roofing & Services LTD | Roofers in Manchester',
    description: 'Professional roofers in Manchester. Roof repairs, installations & emergency services. Fully insured, free quotes, 24/7 availability. Call +44 7514 471046.',
    canonicalUrl: 'https://preview-mg-roofing-services-ltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
